// Материал стенда «Горизонтальный лонгрид».
// Собран из кадра Figma 95:4 («Основа — архитектура экранов»).
// Порядок массива = порядок колонок в ленте. Дописывать статью — дописывать записи.
//
//   buffer — пустая колонка-отбивка (в мобайле превращается в вертикальный пропуск)
//   title  — титул: date + text; ширина колонки считается от окна
//   lead   — врезка: n, text, by
//   head   — заголовок раздела: n, text
//   text   — абзац: n, text  (не влезает по высоте — перетекает в соседнюю колонку)
//   fig    — одна картинка: n, span (в колонках), src, w, h (натуральные)
//   figs   — стопка картинок с вертикальной прокруткой внутри колонки:
//            n, span, label ('each' — номер у каждой, 'outside' — один над стопкой), items[]
//   cap    — подпись: to (номер картинки), arrow (указатель), text, thumb (портрет)
//
// Индексы «NN – NN» — адреса фрагментов, они же якоря в ссылке (#01-05).
// ВНИМАНИЕ: в макете индекс «02 – 11» стоял на двух колонках подряд,
// здесь вторая и все следующие сдвинуты на единицу (02 – 12 … 02 – 15).
window.GORIZONT = [
  { t: "title", date: "28 April /2026", text: "The Evolution of the Grid: \nfrom Position to Algorithm. From Blueprint to Law" },
  { t: "buffer" },
  { t: "lead", n: "01 – 00", text: "A classical grid remembered where things stand. An algorithmic one remembers how to find out. Therein lies the main difference between the old and the new. The printed and the digital.", by: "by Magdalena Major." },
  { t: "text", n: "01 – 01", text: "It is commonly assumed that the question of the grid was settled back in the twentieth century: the Swiss worked it all out, and all that is left for us is to use it carefully. Fortunately, this is a great misconception — and within the short span of this essay I will try to show why, and to explain the causes behind the transformation of the grid and of our attitude towards it." },
  { t: "text", n: "01 – 02", text: "Around 1940 Max Bill first applied a modular grid to book layout, earning the well-deserved title of “father of the grid.” In the second half of the twentieth century Josef Müller-Brockmann took the grid approach to a religious strictness: a grid of 8 modular cells, then 20, then 32. For him the module was “an expression of the will to order and clarity, of objectivity instead of subjectivity.” But inside the new religion lived a curious paradox: the more detailed the grid, the more freedom it gave the designer. And still every layout was assembled and approved by a human — so the demands on the designer’s professionalism and competence kept growing." },
  { t: "buffer" },
  { t: "figs", n: "01", span: 2, label: "each", items: [
  { n: "01", src: "fig-01.svg", w: 679, h: 953 },
  { n: "02", src: "fig-02.svg", w: 679, h: 953 },
  { n: "03", src: "fig-03.svg", w: 679, h: 953 }
] },
  { t: "cap", to: "01", arrow: "←", text: "Grids of 8, 20 and 32 cells with dimensions in ciceros — redrawn after J. Müller-Brockmann, Grid Systems in Graphic Design, 1981", thumb: "thumb-01.webp" },
  { t: "buffer" },
  { t: "text", n: "01 – 03", text: "The religion proved contagious and spread beyond Switzerland. For his devotion to modular order, the Dutchman Wim Crouwel received from his colleagues the nickname Mr. Gridnik — and accepted it like a holy title: the name was later given to his typeface designed for Olivetti typewriters. The utmost point of Crouwel’s faith is the Vormgevers poster for the Stedelijk Museum in Amsterdam (1968): a grid of 57 vertical and 41 horizontal lines is not hidden beneath the layout but printed at full height, and the letters themselves are built out of its cells. The instrument of markup became the image: the grid ceased to be a means of order and turned into its manifesto." },
  { t: "fig", n: "04", span: 2, src: "fig-04.webp", w: 680, h: 1022 },
  { t: "cap", to: "04", arrow: "←", text: "The Vormgevers poster, 1968: the grid printed at full height, the letters built from its cells — W. Crouwel (scan from the collection of the Stedelijk Museum, Amsterdam)", thumb: "thumb-04.webp" },
  { t: "buffer" },
  { t: "text", n: "01 – 04", text: "In essence, the grid of that era is a blueprint. A table of ready-made positions, measured out from edge to edge of the sheet’s format. It could be perfect because everything was known in advance: the format trimmed, the text written and delivered. To use an analogy, the grid of that time is like a suit tailored to an individual measure: the tailor knows the client’s figure before the first cut — and as long as there is one figure, the pattern can be flawless." },
  { t: "text", n: "01 – 05", text: "Brockmann’s own practice was that of such a tailor — he himself described his method as a fitting: design the grid, test it against real material; yes — into production, no — back to the drawing board, and so on until it sits perfectly. The work, then, was a process of constant shuttling between the material already known and the grid of the layout to come. So one may say the grid here was built after the fact — out of the material already lying on the table. I have used this myself in teaching, as an example of the classical principle laid down by Brockmann himself — the principle of the priority of composition over the grid (the principle of good form, in R. Arnheim’s terms). Simply put: composition first, the grid second." },
  { t: "buffer" },
  { t: "fig", n: "05", span: 1, src: "fig-05.svg", w: 339, h: 475 },
  { t: "fig", n: "06", span: 1, src: "fig-06.svg", w: 339, h: 475 },
  { t: "cap", to: "05", arrow: "←  →", text: "One eight-cell grid generates eight illustration formats — redrawn after Müller-Brockmann, ibid., \np. 74", thumb: "thumb-05.webp" },
  { t: "figs", n: "07", span: 1, label: "outside", items: [
  { n: null, src: "fig-07-1.svg", w: 339, h: 476 },
  { n: null, src: "fig-07-2.svg", w: 339, h: 476 },
  { n: null, src: "fig-07-3.svg", w: 339, h: 476 },
  { n: null, src: "fig-07-4.svg", w: 339, h: 476 },
  { n: null, src: "fig-07-5.svg", w: 339, h: 476 },
  { n: null, src: "fig-07-6.svg", w: 339, h: 476 }
] },
  { t: "buffer" },
  { t: "text", n: "01 – 06", text: "In 1962 Karl Gerstner was working on Capital magazine — and a magazine runs for years; what future issues will hold, nobody knows. The grid approach collided with uncertainty, and Gerstner answered it with reserve. His grid still makes an indelible impression on beginning designers, for it seems charmingly intricate, though in essence it is a deeply considered automaton of variability. The page is engineered from 58 micro-units and divides without remainder into 2, 3, 4, 5 or 6 columns — that is, Gerstner defined not so much a grid as a program of variability for the grid. He put it himself: the grid is “a programme for content as yet unknown.” Gerstner was the first to design a rule that generates layouts, rather than a layout that generates rules." },
  { t: "text", n: "01 – 07", text: "To push the tailoring analogy further: he moved from a made-to-measure suit to a pattern with a size run (a term, incidentally, from the same trade) — one construction yields size 44, 48 and 52 alike. Note: only the material was unknown; the magazine’s format itself stood still. And the cutting was still done by the designer-cutter: he looked at the material that had arrived for the issue and chose the variant that fitted best. The grid was conceived as a program, but the program was executed by a human — a compositor, by hand, issue after issue. Gerstner’s genius lies in having invented an automaton that for another half-century could not run without assistance." },
  { t: "fig", n: "08", span: 2, src: "fig-08.svg", w: 680, h: 680 },
  { t: "cap", to: "08", arrow: "←", text: "The Capital grid as a superposition of 4-, 5- and 6-column grids — redrawn (after K. Gerstner, 1962)", thumb: "thumb-08.webp" },
  { t: "fig", n: "09", span: 3, src: "fig-09.webp", w: 1139, h: 641 },
  { t: "cap", to: "09", arrow: "←", text: "The programme enumerates its solutions: variants of the Boîte à musique frame — redrawn (after K. Gerstner, Designing Programmes, 1964)" },
  { t: "fig", n: "10", span: 2, src: "fig-10.webp", w: 680, h: 971 },
  { t: "cap", to: "10", arrow: "←", text: "The frame outlives its author: the memorial poster for Karl Gerstner (1930–2017), built on the Boîte à musique principle" },
  { t: "buffer" },
  { t: "text", n: "01 – 08", text: "To see where the automaton finally started running on its own, we need to understand something about the grid itself." },
  { t: "text", n: "01 – 09", text: "It has been defined in many ways: a framework, a skeleton, a system of guides or force lines — and all of these are at once close and wide of the mark. The term “framework,” say, better describes the support of a form, whereas the grid governs place and space as a whole." },
  { t: "text", n: "01 – 10", text: "So the grid is more accurately defined as a way of organising the space of the format — and the word “space” deserves to be underlined twice. While the format was a printed sheet, it sounded almost like a metaphor: the sheet is motionless, its space ends at its edges. Ruder himself, in his Typographie, avoided the term “space,” replacing it with the narrower “volume,” while the sheet he understood first of all as a plane. Incidentally, the Russian tradition, on the contrary, had been using the term “space” actively since the days of VKhUTEMAS — it figures in Favorsky and Florensky, in Ladovsky and Tarabukin, and in many others. Today the metaphor has materialised. The screen, virtual and quasi-virtual spaces — the format has become space literally: alive, stretching, changeable. And when the character of the space changes (of the format in the narrow sense), the way of organising it changes too — this is the key cause of the grid’s transformation. Layout technology merely answered the call." },
  { t: "buffer" },
  { t: "head", n: "02 – 00", text: "The Sheet and the Screen" },
  { t: "text", n: "02 – 01", text: "A sheet has an edge; a web page has none: everyone’s window has a width of its own. Opening a page, we know its width for certain, since we see the screen directly, while the height of a longread never coincides with the height of the screen. Speaking of the digital format, then, we must keep two formats in mind at once: the format of the screen as what we actually see, and the format of the longread as what is hidden and only thought behind the screen. This, incidentally, largely wrecks the compositional approach to page layout, since the compositional ties between the elements of the first screen and, say, the second, the third or the last are not evident to our “visual judgement” (R. Arnheim’s term)." },
  { t: "text", n: "02 – 02", text: "During scroll the horizontals (force lines, lines of text) are always in motion, while the verticals stay static — which is why, by the way, they carry a predominantly navigational meaning: these are the lines along which the eye descends from top to bottom (assuming vertical scroll). The horizontal lines, in turn, become the bearings." },
  { t: "text", n: "02 – 03", text: "The next important change: content arrives after the designer’s work is done. Like Gerstner, we must lay out in advance, under uncertainty: the headline will run twice as long as in the mockup; there will be now 7 cards, now 17. Layout and composition have to be resolved at the moment of display — and at that moment the designer is not there. The only one standing in for them is the browser — the code." },
  { t: "text", n: "02 – 04", text: "Design’s first answer to this uncertainty was the use of breakpoints: as a rule, we draw at least three mockups — phone, tablet, desktop — and switch between them by window width. In essence, this is the classical positional approach of print design stretched over the web: instead of one blueprint, three — and between them a void in which the layout waits for its next jump. Most people still work this way." },
  { t: "text", n: "02 – 05", text: "Whereas an attempt to solve this problem by the digital means available to us leads to algorithms — executed not by the designer but by the browser.\nLet me repeat: the uncertainty has become double — both the material and the format itself are unknown — and covering it with a reserve of variants is no longer possible: the variants are infinite, while fighting uncertainty by pre-digital means leads to what we already see around us — a uniformity which, as AI takes hold, stops creating added value and will therefore keep losing demand among prospective clients who want to stand out against the common backdrop of tile-and-card AI design." },
  { t: "text", n: "02 – 06", text: "How, then, is the question to be solved? The answer is simple: decide in the present tense. The designer defines the law; the law is fixed in algorithms that compute the positions of elements, or groups of elements, relative to one another and to the format as a whole; and the browser computes by the given algorithms at every opening of the page — in our analogy, the tailor has moved into the fitting room, and the suit is re-cut at the moment it is put on. A single line — repeat(auto-fit, minmax(240px, 1fr)) — counts by itself how many columns there are today. And that is precisely the decision Gerstner used to make by hand, every time — issue after issue, number after number." },
  { t: "text", n: "02 – 07", text: "All in all, if the whole history of the grid is compressed into a single formula:\n\n— Brockmann built the grid after the fact,\n— Gerstner — in advance,\n— the algorithmic grid works on the spot, here and now." },
  { t: "buffer" },
  { t: "lead", n: "02 – 08", text: "A classical metric grid defines ready-made positions; an algorithmic one gives a way of computing them. Roughly speaking: blueprint versus function.", by: "by Magdalena Major." },
  { t: "text", n: "02 – 09", text: "The difference is easy to show on everyday material. Take ten people: each has a first name, a family name, a patronymic. The metric approach lays them out as a table: three columns — first name, family name, patronymic — with numbers down the side; every element gets a ready position, measured geometrically. The algorithmic approach defines a chain instead of positions: the first names line up along one shared line; the family name begins where the first name ended — and ten pixels lower; the patronymic — where the family name ended, and ten lower still. Write this out for all ten — and the line of the build comes out original for each: the names differ in length, and the chain breaks anew every time. Against the vertical, a living line appears. This principle has a name — conjugation: an element’s position is not assigned but determined by the neighbouring element it is conjugated with — the previous one, the next one, or the one standing beside it. Text that builds itself; images that build a modular longread anew every time, depending on their own nature (horizontal, vertical or square) and on the parameters of the browser window — and of the medium on which the site is opened." },
  { t: "text", n: "02 – 10", text: "Notice: nobody assigned the positions — they are computed out of the material itself." },
  { t: "text", n: "02 – 11", text: "Let me note that I am in no way opposing the classics to the digital, positional metric grids to algorithmic ones. Metric and position have not gone anywhere. The accent has shifted: from the geometric to the mobile. And this, in turn, gave the grid what Wolfgang Weingart — the famous rebel of the Basel school, who dreamed of a living, free typography — spoke of back in 1972. But where Weingart pulled the living line by hand — through bending and breaking the rules, each breach demanding justification — today it can arise without hands: from a designer who thinks through the algorithm it lives by. The plasticity of the grid has ceased to be a violation of order and become its product. The designer’s task changes with it: not to compose and describe in rules, but to conceive a principle and realise it in an algorithm. “A column no narrower than 240” is an optical decision taken by the designer before the encounter with the case, because at the moment of that encounter the designer and their eye will not be around." },
  { t: "buffer" },
  { t: "fig", n: "11", span: 2, src: "fig-11.webp", w: 640, h: 827 },
  { t: "fig", n: "12", span: 2, src: "fig-12.webp", w: 640, h: 913 },
  { t: "cap", to: "11", arrow: "←", text: "W. Weingart’s covers for Typografische Monatsblätter — No. 1/1972 and No. 3/1973: type steps off the composed line in steps and shifts, the living line drawn by hand (scans: TM Research Archive)" },
  { t: "text", n: "02 – 12", text: "The algorithmic approach is directly connected to the classical metric (positional) one: it stands on it and extends it in time. Gerstner described the goal of the grid approach as a parameter with “the greatest number of constant factors combined with the greatest possible variability” — the grid as a parameter of balance between uniformity and variety. And within that balance the algorithmic grid pursues the same aspiration, taken to its technological limit. The classics have not aged out; they have transformed: the blueprint became a program, the program became a law. The principle, meanwhile, stays where it has always been — with the designer: they conceive the principle, derive the rules from it, and that body of rules runs in the browser as law — computed, now, by the machine." },
  { t: "text", n: "02 – 13", text: "Very well. But what does it look like, this algorithmic grid?" },
  { t: "text", n: "02 – 14", text: "The subtlety is that an algorithmic grid is rather hard to see. About as hard as seeing the order in the bark of a tree. In a static mockup it simply is not there — its essence is behaviour, what happens when you pull the window by its edge. Which is why learning it from a picture is like learning music from a photograph of a single chord. And why it has only truly opened up now, when a designer can assemble a working grid in code with words and pull the edge of the window themselves. With no intermediary between them and the result." },
  { t: "text", n: "02 – 15", text: "How this looks in action I will show on our own model — the Mapa Grid photo gallery, laid out by vibe-coding." },
  { t: "buffer" }
];
