/* КОЛЛЕКЦИИ каталога M7 — из папки ~/Downloads/GG: папка = коллекция, обложка —
   первая горизонтальная картинка папки (файл назван), nomer — её порядковый в папке,
   kadrov — сколько кадров в коллекции: это число стоит у зеркала (Сергей 07.09).
   Описание пока одно на всех, из макета: в гарнитурах макета нет кириллицы. Русское имя
   и строка коллекции (из КАТАЛОГ.md) лежат рядом — russkoe, stroka — до кириллической гарнитуры. */
window.KOLLEKCII=[
{"imya": "CLLCTN 1", "nomer": "007", "papka": "01 Предмет", "fail": "A_bowl_of_black_noodles_arranged_as_an_exact_spiral_galaxy_wh_bafb3a9f-39e8-4d98-bd2f-34a8f84b47b5_0.png", "oblozhka": "/galereya-m7-dannye/kollekciya-01.jpg", "w": 1232, "h": 928, "opisanie": "Concept, model, and architectural framework of a standard interactive photo gallery, developed as part of a research project.", "russkoe": "Предмет", "stroka": "Одна вещь, у которой подменили одну деталь", "kadrov": 34},
{"imya": "CLLCTN 2", "nomer": "009", "papka": "02 Существо", "fail": "A_desert_tortoise_with_a_shell_resembling_a_brutalist_concret_6f69cc9e-defc-4d9e-a17c-7e27f8ccde38_1.png", "oblozhka": "/galereya-m7-dannye/kollekciya-02.jpg", "w": 1200, "h": 960, "opisanie": "Concept, model, and architectural framework of a standard interactive photo gallery, developed as part of a research project.", "russkoe": "Существо", "stroka": "Живое, собранное из неживого материала", "kadrov": 40},
{"imya": "CLLCTN 3", "nomer": "004", "papka": "03 Усилие", "fail": "A_pair_of_hands_playing_cats_cradle_with_luminous_white_threa_03a43f9f-def5-4106-886b-cee2f7ea2d69_0.png", "oblozhka": "/galereya-m7-dannye/kollekciya-03.jpg", "w": 1344, "h": 896, "opisanie": "Concept, model, and architectural framework of a standard interactive photo gallery, developed as part of a research project.", "russkoe": "Усилие", "stroka": "Тело в работе и то, чем тело работает", "kadrov": 33},
{"imya": "CLLCTN 4", "nomer": "001", "papka": "04 Постройка", "fail": "A_book_with_pages_carved_into_a_descending_amphitheater_open__7d23db50-5ac8-44a7-ba5a-b816de4e9850_0.png", "oblozhka": "/galereya-m7-dannye/kollekciya-04.jpg", "w": 1344, "h": 896, "opisanie": "Concept, model, and architectural framework of a standard interactive photo gallery, developed as part of a research project.", "russkoe": "Постройка", "stroka": "Вещь разворачивается в здание", "kadrov": 31},
{"imya": "CLLCTN 5", "nomer": "001", "papka": "05 Антенна", "fail": "A_dense_field_of_satellite_dishes_all_pointing_toward_one_tin_482fdb3b-e80b-4512-9f62-c2b68ba5d3c7_0.png", "oblozhka": "/galereya-m7-dannye/kollekciya-05.jpg", "w": 1536, "h": 768, "opisanie": "Concept, model, and architectural framework of a standard interactive photo gallery, developed as part of a research project.", "russkoe": "Антенна", "stroka": "Устройства, которые ловят и передают", "kadrov": 31},
{"imya": "CLLCTN 6", "nomer": "001", "papka": "06 Горизонт", "fail": "A_black_sand_dune_crossed_by_a_single_white_zipper_landscape__bc90f0fc-3359-40c1-87da-b15c1d53e9f0_0.png", "oblozhka": "/galereya-m7-dannye/kollekciya-06.jpg", "w": 1600, "h": 686, "opisanie": "Concept, model, and architectural framework of a standard interactive photo gallery, developed as part of a research project.", "russkoe": "Горизонт", "stroka": "Дальний план, где главное — расстояние", "kadrov": 23},
{"imya": "CLLCTN 7", "nomer": "002", "papka": "07 Наборный лист", "fail": "A_cassette_tape_unwinding_into_an_immense_geometric_labyrinth_671e2e0d-7d69-4530-9b47-f6554dc0ee5a_1.png", "oblozhka": "/galereya-m7-dannye/kollekciya-07.jpg", "w": 1456, "h": 816, "opisanie": "Concept, model, and architectural framework of a standard interactive photo gallery, developed as part of a research project.", "russkoe": "Наборный лист", "stroka": "Плоскость, буква, отпечаток", "kadrov": 30}
];
